//
//  FlagsStorage.swift
//  Flags_MVC
//
//  Created by Pavel Krigin on 17.06.2023.
//

import Foundation
import UIKit

final class FlagsStorage {
    
    private let flags: [FlagModel] = [
        
        FlagModel(image: UIImage(named: "Flag_of_Albania.svg")!, name: "Albania"),
        FlagModel(image: UIImage(named: "Flag_of_Algeria.svg")!, name: "Algeria"),
        FlagModel(image: UIImage(named: "Flag_of_Andorra.svg")!, name: "Andorra"),
        FlagModel(image: UIImage(named: "Flag_of_Angola.svg")!, name: "Angola"),
        FlagModel(image: UIImage(named: "Flag_of_Antigua_and_Barbuda.svg")!, name: "Antigua and Barbuda"),
        FlagModel(image: UIImage(named: "Flag_of_Argentina.svg")!, name: "Argentina"),
        FlagModel(image: UIImage(named: "Flag_of_Armenia.svg")!, name: "Armenia"),
        FlagModel(image: UIImage(named: "Flag_of_Australia.svg")!, name: "Australia"),
        FlagModel(image: UIImage(named: "Flag_of_Austria.svg")!, name: "Austria"),
        FlagModel(image: UIImage(named: "Flag_of_Azerbaijan.svg")!, name: "Azerbaijan"),
        FlagModel(image: UIImage(named: "Flag_of_Bahrain.svg")!, name: "Bahrain"),
        FlagModel(image: UIImage(named: "Flag_of_Bangladesh.svg")!, name: "Bangladesh"),
        FlagModel(image: UIImage(named: "Flag_of_Barbados.svg")!, name: "Barbados"),
        FlagModel(image: UIImage(named: "Flag_of_Belarus.svg")!, name: "Belarus"),
        FlagModel(image: UIImage(named: "Flag_of_Belgium_(civil).svg")!, name: "Belgium"),
        FlagModel(image: UIImage(named: "Flag_of_Belize.svg")!, name: "Belize"),
        FlagModel(image: UIImage(named: "Flag_of_Benin.svg")!, name: "Benin"),
        FlagModel(image: UIImage(named: "Flag_of_Bhutan.svg")!, name: "Bhutan"),
        FlagModel(image: UIImage(named: "Flag_of_Bolivia_(state).svg")!, name: "Bolivia"),
        FlagModel(image: UIImage(named: "Flag_of_Bosnia_and_Herzegovina.svg")!, name: "Herzegovina"),
        FlagModel(image: UIImage(named: "Flag_of_Botswana.svg")!, name: "Botswana"),
        FlagModel(image: UIImage(named: "Flag_of_Brazil.svg")!, name: "Brazil"),
        FlagModel(image: UIImage(named: "Flag_of_Brunei.svg")!, name: "Brunei"),
        FlagModel(image: UIImage(named: "Flag_of_Bulgaria.svg")!, name: "Bulgaria"),
        FlagModel(image: UIImage(named: "Flag_of_Burkina_Faso.svg")!, name: "Burkina_Faso"),
        FlagModel(image: UIImage(named: "Flag_of_Burundi.svg")!, name: "Burundi"),
        FlagModel(image: UIImage(named: "Flag_of_Cambodia.svg")!, name: "Cambodia"),
        FlagModel(image: UIImage(named: "Flag_of_Cameroon.svg")!, name: "Cameroon"),
        FlagModel(image: UIImage(named: "Flag_of_Canada_(Pantone).svg")!, name: "Canada"),
        FlagModel(image: UIImage(named: "Flag_of_Cape_Verde.svg")!, name: "Cape Verde"),
        FlagModel(image: UIImage(named: "Flag_of_Chad.svg")!, name: "Chad"),
        FlagModel(image: UIImage(named: "Flag_of_Chile.svg")!, name: "Chile"),
        FlagModel(image: UIImage(named: "Flag_of_Colombia.svg")!, name: "Colombia"),
        FlagModel(image: UIImage(named: "Flag_of_Costa_Rica_(state).svg")!, name: "Rica"),
        FlagModel(image: UIImage(named: "Flag_of_Côte_d_Ivoire.svg")!, name: "Côte d Ivoire"),
        FlagModel(image: UIImage(named: "Flag_of_Croatia.svg")!, name: "Croatia"),
        FlagModel(image: UIImage(named: "Flag_of_Cuba.svg")!, name: "Cuba"),
        FlagModel(image: UIImage(named: "Flag_of_Cyprus.svg")!, name: "Cyprus"),
        FlagModel(image: UIImage(named: "Flag_of_Denmark.svg")!, name: "Denmark"),
        FlagModel(image: UIImage(named: "Flag_of_Djibouti.svg")!, name: "Djibouti"),
        FlagModel(image: UIImage(named: "Flag_of_Dominica.svg")!, name: "Dominica"),
        FlagModel(image: UIImage(named: "Flag_of_East_Timor.svg")!, name: "East Timor"),
        FlagModel(image: UIImage(named: "Flag_of_Ecuador.svg")!, name: "Ecuador"),
        FlagModel(image: UIImage(named: "Flag_of_Egypt.svg")!, name: "Egypt"),
        FlagModel(image: UIImage(named: "Flag_of_El_Salvador.svg")!, name: "El Salvador"),
        FlagModel(image: UIImage(named: "Flag_of_Equatorial_Guinea.svg")!, name: "Equatorial Guinea"),
        FlagModel(image: UIImage(named: "Flag_of_Eritrea.svg")!, name: "Eritrea"),
        FlagModel(image: UIImage(named: "Flag_of_Estonia.svg")!, name: "Estonia"),
        FlagModel(image: UIImage(named: "Flag_of_Eswatini.svg")!, name: "Eswatini"),
        FlagModel(image: UIImage(named: "Flag_of_Ethiopia.svg")!, name: "Ethiopia"),
        FlagModel(image: UIImage(named: "Flag_of_Fiji.svg")!, name: "Fiji"),
        FlagModel(image: UIImage(named: "Flag_of_Finland.svg")!, name: "Finland"),
        FlagModel(image: UIImage(named: "Flag_of_France_(1794–1815,_1830–1974,_2020–present).svg")!, name: "France"),
        FlagModel(image: UIImage(named: "Flag_of_Gabon.svg")!, name: "Gabon"),
        FlagModel(image: UIImage(named: "Flag_of_Georgia.svg")!, name: "Georgia"),
        FlagModel(image: UIImage(named: "Flag_of_Germany.svg")!, name: "Germany"),
        FlagModel(image: UIImage(named: "Flag_of_Ghana.svg")!, name: "Ghana"),
        FlagModel(image: UIImage(named: "Flag_of_Greece.svg")!, name: "Greece"),
        FlagModel(image: UIImage(named: "Flag_of_Grenada.svg")!, name: "Grenada"),
        FlagModel(image: UIImage(named: "Flag_of_Guatemala.svg")!, name: "Guatemala"),
        FlagModel(image: UIImage(named: "Flag_of_Guinea-Bissau.svg")!, name: "Guinea Bissau"),
        FlagModel(image: UIImage(named: "Flag_of_Guinea.svg")!, name: "Guinea"),
        FlagModel(image: UIImage(named: "Flag_of_Guyana.svg")!, name: "Guyana"),
        FlagModel(image: UIImage(named: "Flag_of_Haiti.svg")!, name: "Haiti"),
        FlagModel(image: UIImage(named: "Flag_of_Honduras.svg")!, name: "Honduras"),
        FlagModel(image: UIImage(named: "Flag_of_Hungary.svg")!, name: "Hungary"),
        FlagModel(image: UIImage(named: "Flag_of_Iceland.svg")!, name: "Iceland"),
        FlagModel(image: UIImage(named: "Flag_of_India.svg")!, name: "India"),
        FlagModel(image: UIImage(named: "Flag_of_Indonesia.svg")!, name: "Indonesia"),
        FlagModel(image: UIImage(named: "Flag_of_Iran.svg")!, name: "Iran"),
        FlagModel(image: UIImage(named: "Flag_of_Iraq.svg")!, name: "Iraq"),
        FlagModel(image: UIImage(named: "Flag_of_Ireland.svg")!, name: "Ireland"),
        FlagModel(image: UIImage(named: "Flag_of_Israel.svg")!, name: "Israel"),
        FlagModel(image: UIImage(named: "Flag_of_Italy.svg")!, name: "Italy"),
        FlagModel(image: UIImage(named: "Flag_of_Jamaica.svg")!, name: "Jamaica"),
        FlagModel(image: UIImage(named: "Flag_of_Japan.svg")!, name: "Japan"),
        FlagModel(image: UIImage(named: "Flag_of_Jordan.svg")!, name: "Jordan"),
        FlagModel(image: UIImage(named: "Flag_of_Kazakhstan.svg")!, name: "Kazakhstan"),
        FlagModel(image: UIImage(named: "Flag_of_Kenya.svg")!, name: "Kenya"),
        FlagModel(image: UIImage(named: "Flag_of_Kiribati.svg")!, name: "Kiribati"),
        FlagModel(image: UIImage(named: "Flag_of_Kuwait.svg")!, name: "Kuwait"),
        FlagModel(image: UIImage(named: "Flag_of_Kyrgyzstan.svg")!, name: "Kyrgyzstan"),
        FlagModel(image: UIImage(named: "Flag_of_Laos.svg")!, name: "Laos"),
        FlagModel(image: UIImage(named: "Flag_of_Latvia.svg")!, name: "Latvia"),
        FlagModel(image: UIImage(named: "Flag_of_Lebanon.svg")!, name: "Lebanon"),
        FlagModel(image: UIImage(named: "Flag_of_Lesotho.svg")!, name: "Lesotho"),
        FlagModel(image: UIImage(named: "Flag_of_Liberia.svg")!, name: "Liberia"),
        FlagModel(image: UIImage(named: "Flag_of_Libya.svg")!, name: "Libya"),
        FlagModel(image: UIImage(named: "Flag_of_Liechtenstein.svg")!, name: "Liechtenstein"),
        FlagModel(image: UIImage(named: "Flag_of_Lithuania.svg")!, name: "Lithuania"),
        FlagModel(image: UIImage(named: "Flag_of_Luxembourg.svg")!, name: "Luxembourgnstein"),
        FlagModel(image: UIImage(named: "Flag_of_Madagascar.svg")!, name: "Madagascar"),
        FlagModel(image: UIImage(named: "Flag_of_Malawi.svg")!, name: "Malawi"),
        FlagModel(image: UIImage(named: "Flag_of_Malaysia.svg")!, name: "Malaysia"),
        FlagModel(image: UIImage(named: "Flag_of_Maldives.svg")!, name: "Maldives"),
        FlagModel(image: UIImage(named: "Flag_of_Mali.svg")!, name: "Mali"),
        FlagModel(image: UIImage(named: "Flag_of_Malta.svg")!, name: "Malta"),
        FlagModel(image: UIImage(named: "Flag_of_Mauritania.svg")!, name: "Mauritania"),
        FlagModel(image: UIImage(named: "Flag_of_Mauritius.svg")!, name: "Mauritius"),
        FlagModel(image: UIImage(named: "Flag_of_Mexico.svg")!, name: "Mexico"),
        FlagModel(image: UIImage(named: "Flag_of_Moldova.svg")!, name: "Moldova"),
        FlagModel(image: UIImage(named: "Flag_of_Monaco.svg")!, name: "Monaco"),
        FlagModel(image: UIImage(named: "Flag_of_Mongolia.svg")!, name: "Mongolia"),
        FlagModel(image: UIImage(named: "Flag_of_Montenegro.svg")!, name: "Montenegro"),
        FlagModel(image: UIImage(named: "Flag_of_Morocco.svg")!, name: "Morocco"),
        FlagModel(image: UIImage(named: "Flag_of_Mozambique.svg")!, name: "Mozambique"),
        FlagModel(image: UIImage(named: "Flag_of_Myanmar.svg")!, name: "Myanmar"),
        FlagModel(image: UIImage(named: "Flag_of_Namibia.svg")!, name: "Namibia"),
        FlagModel(image: UIImage(named: "Flag_of_Nauru.svg")!, name: "Nauru"),
        FlagModel(image: UIImage(named: "Flag_of_Nepal.svg")!, name: "Nepal"),
        FlagModel(image: UIImage(named: "Flag_of_New_Zealand.svg")!, name: "New Zealand"),
        FlagModel(image: UIImage(named: "Flag_of_Nicaragua.svg")!, name: "Nicaragua"),
        FlagModel(image: UIImage(named: "Flag_of_Niger.svg")!, name: "Niger"),
        FlagModel(image: UIImage(named: "Flag_of_Nigeria.svg")!, name: "Nigeria"),
        FlagModel(image: UIImage(named: "Flag_of_North_Korea.svg")!, name: "North_Korea"),
        FlagModel(image: UIImage(named: "Flag_of_North_Macedonia.svg")!, name: "North Macedonia"),
        FlagModel(image: UIImage(named: "Flag_of_Norway.svg")!, name: "Norway"),
        FlagModel(image: UIImage(named: "Flag_of_Oman.svg")!, name: "Oman"),
        FlagModel(image: UIImage(named: "Flag_of_Pakistan.svg")!, name: "Pakistan"),
        FlagModel(image: UIImage(named: "Flag_of_Palau.svg")!, name: "Palau"),
        FlagModel(image: UIImage(named: "Flag_of_Panama.svg")!, name: "Panama"),
        FlagModel(image: UIImage(named: "Flag_of_Papua_New_Guinea.svg")!, name: "Papua New Guinea"),
        FlagModel(image: UIImage(named: "Flag_of_Paraguay.svg")!, name: "Paraguay"),
        FlagModel(image: UIImage(named: "Flag_of_Peru_(state).svg")!, name: "Peru"),
        FlagModel(image: UIImage(named: "Flag_of_Poland.svg")!, name: "Poland"),
        FlagModel(image: UIImage(named: "Flag_of_Portugal.svg")!, name: "Portugal"),
        FlagModel(image: UIImage(named: "Flag_of_Qatar.svg")!, name: "Qatar"),
        FlagModel(image: UIImage(named: "Flag_of_Romania.svg")!, name: "Romania"),
        FlagModel(image: UIImage(named: "Flag_of_Russia.svg")!, name: "Russia"),
        FlagModel(image: UIImage(named: "Flag_of_Rwanda.svg")!, name: "Rwanda"),
        FlagModel(image: UIImage(named: "Flag_of_Saint_Kitts_and_Nevis.svg")!, name: "Kitts and Nevis"),
        FlagModel(image: UIImage(named: "Flag_of_Saint_Lucia.svg")!, name: "Saint Lucia"),
        FlagModel(image: UIImage(named: "Flag_of_Saint_Vincent_and_the_Grenadines.svg")!, name: "Saint Vincent and the Grenadines"),
        FlagModel(image: UIImage(named: "Flag_of_Samoa.svg")!, name: "Samoa"),
        FlagModel(image: UIImage(named: "Flag_of_San_Marino.svg")!, name: "San Marino"),
        FlagModel(image: UIImage(named: "Flag_of_São_Tomé_and_Príncipe.svg")!, name: "São Tomé and Príncipe"),
        FlagModel(image: UIImage(named: "Flag_of_Saudi_Arabia.svg")!, name: "Saudi Arabia"),
        FlagModel(image: UIImage(named: "Flag_of_Serbia.svg")!, name: "Serbia"),
        FlagModel(image: UIImage(named: "Flag_of_Seychelles.svg")!, name: "Seychelles"),
        FlagModel(image: UIImage(named: "Flag_of_Sierra_Leone.svg")!, name: "Sierra Leone"),
        FlagModel(image: UIImage(named: "Flag_of_Singapore.svg")!, name: "Singapore"),
        FlagModel(image: UIImage(named: "Flag_of_Slovakia.svg")!, name: "Slovakia"),
        FlagModel(image: UIImage(named: "Flag_of_Slovenia.svg")!, name: "Slovenia"),
        FlagModel(image: UIImage(named: "Flag_of_Somalia.svg")!, name: "Somalia"),
        FlagModel(image: UIImage(named: "Flag_of_South_Africa.svg")!, name: "South Africa"),
        FlagModel(image: UIImage(named: "Flag_of_South_Korea.svg")!, name: "South Korea"),
        FlagModel(image: UIImage(named: "Flag_of_South_Sudan.svg")!, name: "South Sudan"),
        FlagModel(image: UIImage(named: "Flag_of_Spain.svg")!, name: "Spain"),
        FlagModel(image: UIImage(named: "Flag_of_Sri_Lanka.svg")!, name: "Sri Lanka"),
        FlagModel(image: UIImage(named: "Flag_of_Sudan.svg")!, name: "Sudan"),
        FlagModel(image: UIImage(named: "Flag_of_Suriname.svg")!, name: "Suriname"),
        FlagModel(image: UIImage(named: "Flag_of_Sweden.svg")!, name: "Sweden"),
        FlagModel(image: UIImage(named: "Flag_of_Switzerland.svg")!, name: "Switzerland"),
        FlagModel(image: UIImage(named: "Flag_of_Syria.svg")!, name: "Syria"),
        FlagModel(image: UIImage(named: "Flag_of_Tajikistan.svg")!, name: "Tajikistan"),
        FlagModel(image: UIImage(named: "Flag_of_Tanzania.svg")!, name: "Tanzania"),
        FlagModel(image: UIImage(named: "Flag_of_Thailand.svg")!, name: "Thailand"),
        FlagModel(image: UIImage(named: "Flag_of_the_Bahamas.svg")!, name: "Bahamas"),
        FlagModel(image: UIImage(named: "Flag_of_the_Central_African_Republic.svg")!, name: "The Central African Republic"),
        FlagModel(image: UIImage(named: "Flag_of_the_Comoros.svg")!, name: "The Comoros"),
        FlagModel(image: UIImage(named: "Flag_of_the_Democratic_Republic_of_the_Congo.svg")!, name: "Democratic Republic of the Congo"),
        FlagModel(image: UIImage(named: "Flag_of_the_Dominican_Republic.svg")!, name: "Dominican Republic"),
        FlagModel(image: UIImage(named: "Flag_of_the_Federated_States_of_Micronesia.svg")!, name: "Micronesia"),
        FlagModel(image: UIImage(named: "Flag_of_The_Gambia.svg")!, name: "Gambia"),
        FlagModel(image: UIImage(named: "Flag_of_the_Marshall_Islands.svg")!, name: "The Marshall Islands"),
        FlagModel(image: UIImage(named: "Flag_of_the_Netherlands.svg")!, name: "The Netherlands"),
        FlagModel(image: UIImage(named: "Flag_of_the_People_s_Republic_of_China.svg")!, name: "China"),
        FlagModel(image: UIImage(named: "Flag_of_the_Philippines.svg")!, name: "The Philippines"),
        FlagModel(image: UIImage(named: "Flag_of_the_Republic_of_the_Congo.svg")!, name: "Republic of the Congo"),
        FlagModel(image: UIImage(named: "Flag_of_the_Solomon_Islands.svg")!, name: "The Solomon Islands"),
        FlagModel(image: UIImage(named: "Flag_of_the_United_Arab_Emirates.svg")!, name: "UAE"),
        FlagModel(image: UIImage(named: "Flag_of_the_United_Kingdom_(3-5).svg")!, name: "United Kingdom"),
        FlagModel(image: UIImage(named: "Flag_of_the_United_States.svg")!, name: "United States"),
        FlagModel(image: UIImage(named: "Flag_of_Togo.svg")!, name: "Togo"),
        FlagModel(image: UIImage(named: "Flag_of_Tonga.svg")!, name: "Tonga"),
        FlagModel(image: UIImage(named: "Flag_of_Trinidad_and_Tobago.svg")!, name: "Trinidad and Tobago"),
        FlagModel(image: UIImage(named: "Flag_of_Tunisia.svg")!, name: "Tunisia"),
        FlagModel(image: UIImage(named: "Flag_of_Turkey.svg")!, name: "Turkey"),
        FlagModel(image: UIImage(named: "Flag_of_Turkmenistan.svg")!, name: "Turkmenistan"),
        FlagModel(image: UIImage(named: "Flag_of_Tuvalu.svg")!, name: "Tuvalu"),
        FlagModel(image: UIImage(named: "Flag_of_Uganda.svg")!, name: "Uganda"),
        FlagModel(image: UIImage(named: "Flag_of_Ukraine.svg")!, name: "Ukraine"),
        FlagModel(image: UIImage(named: "Flag_of_Uruguay.svg")!, name: "Uruguay"),
        FlagModel(image: UIImage(named: "Flag_of_Uzbekistan.svg")!, name: "Uzbekistan"),
        FlagModel(image: UIImage(named: "Flag_of_Vanuatu.svg")!, name: "Vanuatu"),
        FlagModel(image: UIImage(named: "Flag_of_Venezuela_(state).svg")!, name: "Venezuela"),
        FlagModel(image: UIImage(named: "Flag_of_Vietnam.svg")!, name: "Vietnam"),
        FlagModel(image: UIImage(named: "Flag_of_Yemen.svg")!, name: "Yemen"),
        FlagModel(image: UIImage(named: "Flag_of_Zambia.svg")!, name: "Zambia"),
        FlagModel(image: UIImage(named: "Flag_of_Zimbabwe.svg")!, name: "Zimbabwe")
    ]
    
    func getFlagsForQuiz() -> [FlagModel] {
        Array(flags.choose(3))// разобраться с ф-ей, чтобы выбирал три рандомных варианта
    }
    
}

extension Collection {
    func choose(_ n: Int) -> ArraySlice<Element> { shuffled().prefix(n) }
}
